# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mhuebert/docker-java-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}--{{ checksum "shadow-cljs.edn"}}

      - run:
          command: npm install;

      - run:
          command: npx shadow-cljs start;
      - run:
          command: npx shadow-cljs clj-eval :foo-1;
      - run:
          command: npx shadow-cljs stop;
      - run:
          command: npx shadow-cljs start && npx shadow-cljs clj-eval :foo-2;

      - run:
          command: cat target/shadow-cljs/shadow-cljs.log.0 2> /dev/null
          working_directory: ~/project/editor
          when: on_fail

      - save_cache:
          paths:
            - ~/project/node_modules
            - ~/project/target
            - ~/.m2
          key: v3-dependencies-{{ checksum "package.json" }}--{{ checksum "shadow-cljs.edn"}}


